.TH extract 1 "October 16, 2011" "version 1.0" "USER COMMANDS"
.SH NAME
extract \- extract articles from a Wikipedia XML database.

.SH SYNOPSIS
.B extract [-d directory]

.SH DESCRIPTION 
The extract utility reads a Wikipedia XML database of articles from
standard input and extracts MediaWiki markup for each article. The
output is printed to standard output, or, if the \-d parameter is
specified, to files in a directory.

.PP
extract can work with very large databases (tens of gigabytes) without
running our of memory.

.PP 
If output directory is not specified, articles are printed to standard
output and delimited by page feeds (C character '\\f').

.SH OPTIONS
.TP
\-d the otuput directory
If set, articles will be saved in the directory with each article in a
separate file. The files will be named after the articles.

.SH EXAMPLES
.TP
Command:
.nf
cat ../wikipedia/data/enwiki-20110620-pages-articles.xml | extract
.fi
.TP
Output (truncated):
.nf
{{Redirect|Anarchist|the fictional character|Anarchist (comics)}}
{{Redirect|Anarchists}}
{{Good article}}
{{pp-move-indef}}
{{Anarchism sidebar}}
\'\'\'Anarchism\'\'\' is a [[political philosophy]] 
.fi
