.TH ngrams-freq-filter 1 "October 16, 2011" "version 1.0" "USER COMMANDS"
.SH NAME
ngrams-freq-filter \- filters out ngrams with low counts.

.SH SYNOPSIS
.B ngrams-freq-filter [-t THRESHOLD]

.SH DESCRIPTION 
The ngrams-freq-filter utility reads ngrams produced by the 'ngram'
utility from standard input and filters out ngrams with counts below a
user-specified threshold. The output is written to standard output.

.SH OPTIONS
.TP
\-t THRESHOLD
specifies count threshold. ngrams with counts below this number will
not be included in the output. Default value: 1.

.SH EXAMPLES
.TP
Command:
.nf
echo -e "this is a test\\nthis is yet another test" | \\
ngrams -n 2 | ngrams-freq-filter -t 2
.fi
.TP
Output:
.nf
6
<s> this	2
test </s>	2
this is	2
.fi
