.TH wiki-textify 1 "October 16, 2011" "version 1.0" "USER COMMANDS"
.SH NAME
.B wiki-textify 
\- transform MediaWiki markup into plaintext.

.SH SYNOPSIS
.B wiki-textify 
[-h, --ignore-headings]

.SH DESCRIPTION 
.B wiki-textify
takes MediaWiki input from standard input and outputs
plaintext, ignoring all metadata, tables, comments and other
formatting.

All input articles must be followed by a '\\f' (page feed) character,
and they will also be so delimited in the output.

In the output, paragraphs and headings are delimited by at least two
linesbreaks. Sentences within paragraphs are either on the same line
or separated by a single linebreak.

.SH OPTIONS
.TP
\-h, \-\-ignore-headings
If set, headings will be ignored in the output.

.SH EXAMPLES

.TP
Command:
.nf
echo -e "==Test section==\\n''This is a test'' of converting\\
 [markup|MediaWiki] markup into [plaintext]\\n\\f" | wiki-textify 
.fi
.TP
Output:
.nf
Test section

This is a test of converting MediaWiki markup into plaintext
^L
.fi

.SH AUTHOR
Autocorpus was written by Maciej Pacula (maciej.pacula@gmail.com).

The project website is http://mpacula.com/autocorpus

.SH SEE ALSO
.BR autocorpus (7),
.BR ngrams (1),
.BR ngrams (5),
.BR ngrams-freq-filter (1),
.BR ngrams-sort (1),
.BR sentences (1),
.BR tokenize (1),
.BR wiki-articles (1),
