Document: autocorpus
Title: Debian autocorpus Manual
Author: <insert document author here>
Abstract: This manual describes what autocorpus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/autocorpus/autocorpus.sgml.gz

Format: postscript
Files: /usr/share/doc/autocorpus/autocorpus.ps.gz

Format: text
Files: /usr/share/doc/autocorpus/autocorpus.text.gz

Format: HTML
Index: /usr/share/doc/autocorpus/html/index.html
Files: /usr/share/doc/autocorpus/html/*.html
